#!/bin/sh

#######################################################################
# Task:                                                               #
#   Shell script to start guiff                                       #
#######################################################################

java -jar $(dirname $0)/lib/swing-${project.version}.jar $@

exit 0
